QTWEATHER_VERSION = 1.0
# QTWEATHER_SITE = $(BR2_PACKAGE_SOURCE_DIR)
QTWEATHER_SITE = $(QTWEATHER_PKGDIR)
QTWEATHER_SITE_METHOD = local
QTWEATHER_DEPENDENCIES = qt6base qt6declarative

QTWEATHER_CMAKE_ARGS = \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr

$(eval $(cmake-package))