QTCALC_VERSION = 1.0
# QTCALCULATOR_SITE = $(BR2_PACKAGE_SOURCE_DIR)
QTCALC_SITE = $(QTCALC_PKGDIR)
QTCALC_SITE_METHOD = local
QTCALC_DEPENDENCIES = qt6base qt6declarative

QTCALC_CMAKE_ARGS = \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr

$(eval $(cmake-package))